language: python
sudo: false
cache:
  directories:
    - ~/.cache/pip
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
python:
  - "2.7"
before_install:
  - pip install -U pip
  - pip install wheel
install:
  - pip install pytest
  - pip install -r requirements.txt
  - pip install -e .
script: "pytest"
after_success:
  - coveralls
